# Generated by Django 3.0.5 on 2020-04-20 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200420_2109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Χρήστης', 'verbose_name_plural': 'Χρήστες'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_img',
        ),
    ]
