# Generated by Django 3.0.5 on 2020-04-20 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_profile_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
